export const FETCH_MEMBER = 'FETCH_MEMBER'
export const FETCH_MY_INTRODUCE = 'FETCH_MY_INTRODUCE'
//게시판
export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'
export const FETCH_COMMENT_LIST = 'FETCH_COMMENT_LIST'
export const FETCH_COMMENT = 'FETCH_COMMENT'
//공지사항
export const FETCH_NOTICE_LIST = 'FETCH_NOTICE_LIST'
export const FETCH_NOTICE = 'FETCH_NOTICE'
//스터디
export const FETCH_STUDY_MEMBER_LIST = 'FETCH_STUDY_MEMBER_LIST'
// 수강 리스트
export const FETCH_LECTURE_LIST = 'FETCH_LECTURE_LIST'
//최근강의리스트
export const FETCH_LATEST_LECTURE = 'FETCH_LATEST_LECTURE' 
// 회원관리
export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST'