export const FETCH_MEMBER = 'FETCH_MEMBER'
export const FETCH_MY_INTRODUCE = 'FETCH_MY_INTRODUCE'
//게시판
export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'
export const FETCH_COMMENT_LIST = 'FETCH_COMMENT_LIST'
export const FETCH_COMMENT = 'FETCH_COMMENT'
//공지사항
export const FETCH_NOTICE_LIST = 'FETCH_NOTICE_LIST'
export const FETCH_NOTICE = 'FETCH_NOTICE' 